# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: bankofwine-serverless-api
frameworkVersion: "*"
useDotenv: true

provider:
  name: aws
  profile: blinkers
  runtime: nodejs16.x
  region: ap-northeast-2
  stage: ${opt:stage, "dev"}
  environment:
    STAGE: ${self:provider.stage}
  memorySize: 512
  timeout: 29
  logRetentionInDays: 14
  tracing:
    lambda: true
  deploymentBucket:
    name: bankofwine-serverless-api-${self:provider.stage}
    serverSideEncryption: AES256
  iam:
    role:
      name: bankofwine-serverless-role-${self:provider.stage}
      statements:
        - Effect: "Allow"
          Action:
            - cloudformation:*
            - logs:*
            - lambda:*
            - s3:*
          Resource: "*"

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-plugin-warmup
  - serverless-offline

custom:
  warmup:
    default:
      enabled: true
      prewarm: true # Run WarmUp immediately after a deploy lambda
      events:
        - schedule: rate(5 minutes)
      logRetentionInDays: 14
  webpack:
    excludeRegex: \.ts|test|\.map
    includeModules:
      forceExclude:
        - aws-sdk
        - "@aws-sdk/client-lambda"

package:
  individually: true
  patterns:
    - "./src/prisma/*"

functions:
  graphql:
    handler: src/serverless.handler
    name: graphql-${self:provider.stage}
    events:
      - http:
          cors: true
          path: /graphql
          method: any
